### ISSUE TITLE
Attempting to build Flatpak package; puzzle windows fail to embed and instantly close

### ISSUE THREAD

**Issue by HugLifeTiZ** [bluesabre/sgt-launcher#8]
Hi there. I'm looking to build a Flatpak package for this nice launcher to make it more easily installable everywhere, since at present it only seems to be packaged in Ubuntu. [My progress on the manifest is here.](https://github.com/HugLifeTiZ/flathub/tree/sgt-launcher) Python modules are kind of a pain, then I ended up having to make a tarball distribution of the .png icons because it doesn't include them and expects you to use imagemagick to generate them.

What I am stuck on at present is that the launcher can't actually embed any applications. It starts up any given application, but it immediately closes instead of embedding. There's no useful information printed to stdout or stderr. Do you have any insight on this?

**Comment by bluesabre** [comment]
This sounds really similar to how the app currently behaves on Wayland and GNOME (not even on Wayland). I'm probably going to add a fallback mode that doesn't do the embedding.

**Comment by bluesabre** [comment]
@HugLifeTiZ I've got a branch called `wayland-support` that should now work around this issue. Instead of attempting (and failing) to embed the game, the game window will instead be shown while the launcher is hidden. The launcher will use this behavior for Wayland, GNOME sessions, and when packaged as a flatpak.

Let me know if you want to test this out before I merge it in and do a new release. Thanks!


https://user-images.githubusercontent.com/1894517/132847272-669d6f2f-fdbd-49f5-99e4-1a20de20e2ea.mp4

**Comment by HugLifeTiZ** [comment]
Yeah, that looks like that will do just nicely. I will try building the Flatpak with this branch and get back to you. Thanks for your work on this! :)

**Comment by HugLifeTiZ** [comment]
Okay, looks like it works! Thanks!

**Comment by bluesabre** [comment]
Thanks for the follow-up! 0.2.7 has been released.

https://github.com/bluesabre/sgt-launcher/releases/tag/sgt-launcher-0.2.7
